# Generated by Django 3.0.6 on 2020-10-05 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('profession', models.CharField(max_length=64)),
                ('organization', models.CharField(max_length=64)),
                ('working_city', models.CharField(max_length=32)),
                ('phone', models.IntegerField()),
            ],
            options={
                'db_table': 'home_friends',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Create_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=225, null=True)),
                ('message', models.TextField()),
                ('posted_time', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'home_posts',
                'managed': True,
            },
        ),
    ]
