# Generated by Django 3.0.6 on 2020-10-09 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='create_post',
            table=None,
        ),
        migrations.AlterModelTable(
            name='friends',
            table=None,
        ),
    ]
